DROP TRIGGER IF EXISTS dues_payments_sync_finance ON dues_payments;
DROP TRIGGER IF EXISTS dues_payments_delete_finance ON dues_payments;

DROP FUNCTION IF EXISTS sync_dues_payment_to_finance();
DROP FUNCTION IF EXISTS delete_dues_payment_finance();

-- Remove finance rows that were generated by this integration.
DELETE FROM cash_transactions
WHERE id IN (
    SELECT cash_transaction_id
    FROM dues_finance_links
);

DROP TABLE IF EXISTS dues_finance_links;
